### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ajkl2533** [alexreardon/tiny-warning#12]
Hi, would you mind adding the MIT license file to the repo & the npm package? MIT license actually requires full license text to be distributed along the source code. You can find license text here https://opensource.org/licenses/MIT. 

Many thanks.

**Comment by Eli-Black-Work** [comment]
Would be great to see a license file added :)

**Comment by alexreardon** [comment]
Will do

**Comment by Eli-Black-Work** [comment]
Thanks, man! :)

**Comment by ghost** [comment]
Hoping to see a LICENSE file added. We'd like to refer to this file as part of our auto-license retrieval.

**Comment by Eli-Black-Work** [comment]
Hi @alexreardon, sorry to nag, but has there been any update on this? It looks like there are a lot of packages using this package :)

**Comment by alexreardon** [comment]
I'll do this soon :)

**Comment by Eli-Black-Work** [comment]
Cool, thanks :)
